CREATE WAREHOUSE IF NOT EXISTS RETAIL_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  COMMENT = 'Warehouse for retail sales platform project';

  CREATE DATABASE IF NOT EXISTS RETAIL_DB
  COMMENT = 'Retail Sales Analytics Platform';

  CREATE SCHEMA IF NOT EXISTS RETAIL_DB.STAGING
  COMMENT = 'Raw data loaded from CSV files';

CREATE SCHEMA IF NOT EXISTS RETAIL_DB.BRONZE
  COMMENT = 'Raw data organised by DBT';

CREATE SCHEMA IF NOT EXISTS RETAIL_DB.SILVER
  COMMENT = 'Cleaned and transformed data';

CREATE SCHEMA IF NOT EXISTS RETAIL_DB.GOLD
  COMMENT = 'Analytics ready data for Power BI';

  SHOW SCHEMAS IN DATABASE RETAIL_DB;